// =============================================================================
// quote-email - the two emails the quote Worker sends (2026-10-05)
// =============================================================================
// src/pages/api/quote.ts validates the form, backs it up to R2 and sends two
// messages through the Cloudflare Email Service binding. This module only builds
// them: the owner notification Mary Ann reads (usually on her phone) and the
// customer confirmation. Both are designed pieces in the Atelier language:
//
//   - a Linen page with a Paper card, under a Midnight band that carries the gold
//     Hoop Seal and the Signature Thread wordmark (hosted PNGs on a solid Midnight
//     ground, generated by scripts/generate-favicons.mjs);
//   - a thread-gold rule under the band and running-stitch dividers (dashed brass
//     borders); headings in a serif stack that echoes Fraunces; Claret only for the
//     one action and the rush flag.
//
// Email constraints this respects: table layout, inline styles only, 600px max,
// no web fonts, no SVG, no background images, no flex or grid, a bulletproof
// button built from a table cell, images by absolute URL with width, height and
// alt, nothing that stops reading when images are blocked, no pure white (so a
// client that inverts colours keeps the contrast), a hidden preheader, and a
// plain-text twin written out by hand rather than stripped from the HTML.
//
// SAFETY: every value that came from the form passes through escapeHtml() before
// it touches the HTML, including attributes (mailto:, tel:). Unit tests in
// quote-email.test.ts feed it hostile input.
//
// Copy rules: only claims the site already makes (reply within 1 business day, a
// custom itemized quote by email, nothing is stitched until the customer
// approves). The three "what happens next" lines and the contact details come
// from Sanity at send time when available (thankYouPage.nextSteps,
// siteSettings.email / phone / address), with the same words as fallbacks.
// =============================================================================

import { describeUtm, type UtmTags } from './utm.ts';

/** Production origin. Images must resolve from any inbox, so never the request origin. */
export const SITE_URL = 'https://mas-monograms.com';
/** Header art, versioned because public/_headers caches /brand/email-* as immutable. */
export const EMAIL_SEAL_URL = `${SITE_URL}/brand/email-seal-v1.png`;
export const EMAIL_WORDMARK_URL = `${SITE_URL}/brand/email-wordmark-v1.png`;

/** One submission, already validated and trimmed by the Worker. */
export interface QuoteSubmission {
  submissionId: string;
  submittedAt: Date;
  name: string;
  email: string;
  phone: string;
  referral: string;
  itemType: string;
  ownership: string;
  itemDescription: string;
  quantity: string;
  personalization: string;
  monogramStyle: string;
  placement: string;
  size: string;
  threadCount: string;
  fontPreference: string;
  threadColor: string;
  neededBy: string;
  isRush: boolean;
  isGift: boolean;
  notes: string;
  attachmentNames: string[];
  /**
   * Where the visitor came from (utm_source / utm_medium / utm_campaign, already
   * whitelisted by the Worker, src/lib/utm.ts). Owner email only; never shown to
   * the customer.
   */
  utm?: UtmTags;
}

/** Words and contact details read from Sanity at send time (all optional). */
export interface EmailContext {
  businessName?: string;
  email?: string;
  phone?: string;
  city?: string;
  state?: string;
  nextStepsLabel?: string;
  nextSteps?: string[];
}

export interface BuiltEmail {
  subject: string;
  html: string;
  text: string;
}

// Same wording as thankYouPage in Sanity on 2026-10-05; used only if the fetch fails.
const FALLBACK_NEXT_STEPS = [
  "I'll review your request and the details you shared.",
  "I'll send a custom, itemized quote to your email.",
  'Once you approve, I get stitching, and arrange pickup or shipping.',
];

export function escapeHtml(input: string): string {
  return String(input)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Escape, then keep the visitor's line breaks. */
const escLines = (s: string) => escapeHtml(s).replace(/\r?\n/g, '<br/>');

/**
 * The initials the quote prefill writes into Personalization ("Your initials: ABC",
 * the label comes from atelierSettings), so the email can set them large. Only a
 * short run of letters, digits, `&`, dots, spaces or hyphens counts.
 */
export function parseInitials(personalization: string): string | null {
  for (const line of personalization.split(/\r?\n/)) {
    const m = line.match(/initials?\s*:\s*([A-Za-z0-9&.\- ]{1,9})\s*$/i);
    if (m && m[1].trim()) return m[1].trim();
  }
  return null;
}

/** "Fabric: Natural linen" from the prefill's Item description line, if present. */
export function parseFabric(itemDescription: string): string | null {
  for (const line of itemDescription.split(/\r?\n/)) {
    const m = line.match(/^\s*fabric\s*:\s*(.{1,64})$/i);
    if (m && m[1].trim()) return m[1].trim();
  }
  return null;
}

/** "2026-12-01" (the date input) reads as "Tue, Dec 1, 2026"; anything else is shown as typed. */
export function formatNeededBy(value: string): string {
  const m = value.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!m) return value;
  const d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3]));
  if (Number.isNaN(d.getTime()) || d.getUTCDate() !== +m[3]) return value;
  return d.toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC',
  });
}

/** Digits (and a leading +) for a tel: link; null when it is not a usable number. */
export function telHref(phone: string): string | null {
  const digits = phone.replace(/[^\d+]/g, '');
  return digits.replace(/\D/g, '').length >= 7 ? `tel:${digits}` : null;
}

const firstName = (name: string) => name.split(/\s+/)[0] || name;

// ── Palette (Heirloom Coast + Direction D tokens, src/styles/globals.css) ──────
const C = {
  linen: '#f4eee3',
  paper: '#fbf8f1',
  well: '#f6f0e4', // a panel lifted off Paper
  edge: '#d8cfbc',
  hairline: '#e5dccb',
  ink: '#26312e',
  muted: '#5e5a50', // secondary text on Paper, 6.4:1
  midnight: '#0f1b2d',
  indigo: '#28486b',
  gold: '#d9b15f',
  goldLight: '#f0d58a',
  onDarkMuted: '#c8c0b0',
  brass: '#b98a3e', // stitches only, never text
  brassText: '#835a24',
  claret: '#8c3a2e',
};
const SERIF = "Georgia,'Times New Roman',Times,serif";
const SANS = "'Helvetica Neue',Helvetica,Arial,sans-serif";

// ── Building blocks ────────────────────────────────────────────────────────────
const stitch = (top = 24, bottom = 24) =>
  `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:${top}px 0 ${bottom}px 0;"><div style="border-top:2px dashed ${C.brass};height:0;line-height:0;font-size:0;">&nbsp;</div></td></tr></table>`;

const h1 = (inner: string) =>
  `<h1 style="margin:0 0 12px 0;font-family:${SERIF};font-size:28px;line-height:1.2;font-weight:normal;color:${C.midnight};">${inner}</h1>`;

const h2 = (inner: string) =>
  `<h2 style="margin:0 0 12px 0;font-family:${SERIF};font-size:20px;line-height:1.3;font-weight:normal;color:${C.indigo};">${inner}</h2>`;

const para = (inner: string, extra = '') =>
  `<p style="margin:0 0 14px 0;font-family:${SANS};font-size:16px;line-height:1.6;color:${C.ink};word-break:break-word;overflow-wrap:anywhere;${extra}">${inner}</p>`;

const link = (href: string, label: string) =>
  `<a href="${href}" style="color:${C.indigo};text-decoration:underline;">${label}</a>`;

/** A label/value table with hairline rows. Values must already be escaped HTML. */
function details(rows: Array<[string, string | null | undefined | false]>): string {
  const kept = rows.filter(([, v]) => v) as Array<[string, string]>;
  if (!kept.length) return '';
  const tr = kept
    .map(
      ([label, value], i) =>
        `<tr><td valign="top" width="38%" style="padding:9px 12px 9px 0;${i ? `border-top:1px solid ${C.hairline};` : ''}font-family:${SANS};font-size:13px;line-height:1.45;font-weight:bold;color:${C.muted};">${label}</td><td valign="top" style="padding:9px 0;${i ? `border-top:1px solid ${C.hairline};` : ''}font-family:${SANS};font-size:15px;line-height:1.5;color:${C.ink};word-break:break-word;">${value}</td></tr>`,
    )
    .join('');
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">${tr}</table>`;
}

/** Bulletproof button: the colour lives on the cell, so Outlook paints it too. */
const button = (href: string, label: string) =>
  `<table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td bgcolor="${C.claret}" style="background-color:${C.claret};border-radius:999px;"><a href="${href}" style="display:inline-block;padding:13px 26px;white-space:nowrap;font-family:${SANS};font-size:16px;font-weight:bold;line-height:1.2;color:${C.paper};text-decoration:none;border-radius:999px;">${label}</a></td></tr></table>`;

const rushBadge = (label: string) =>
  `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 16px 0;"><tr><td bgcolor="${C.claret}" style="background-color:${C.claret};border-radius:999px;padding:5px 14px;font-family:${SANS};font-size:13px;font-weight:bold;line-height:1.3;letter-spacing:0.04em;color:${C.paper};">${label}</td></tr></table>`;

interface ShellOptions {
  title: string;
  preheader: string;
  /** Short line in the Midnight band under the wordmark. */
  bandLine?: string;
  body: string;
  footer: string;
}

function shell({ title, preheader, bandLine, body, footer }: ShellOptions): string {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="color-scheme" content="light"/><meta name="supported-color-schemes" content="light"/><title>${title}</title></head>
<body style="margin:0;padding:0;background-color:${C.linen};" bgcolor="${C.linen}">
<div style="display:none;max-height:0;max-width:0;overflow:hidden;opacity:0;mso-hide:all;font-size:1px;line-height:1px;color:${C.linen};">${preheader}&#8199;&#847;&#8199;&#847;&#8199;&#847;&#8199;&#847;&#8199;&#847;&#8199;&#847;</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${C.linen}" style="background-color:${C.linen};"><tr><td align="center" style="padding:24px 10px 32px 10px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;">
<tr><td align="center" bgcolor="${C.midnight}" style="background-color:${C.midnight};padding:28px 20px 22px 20px;">
<img src="${EMAIL_SEAL_URL}" width="72" height="72" alt="" style="display:block;border:0;width:72px;height:72px;margin:0 auto;"/>
<img src="${EMAIL_WORDMARK_URL}" width="220" height="31" alt="MAS Monograms" style="display:block;border:0;width:220px;height:31px;margin:14px auto 0 auto;font-family:${SERIF};font-size:22px;line-height:31px;text-align:center;color:${C.goldLight};"/>
${bandLine ? `<p style="margin:14px 0 0 0;font-family:${SANS};font-size:13px;line-height:1.4;letter-spacing:0.08em;color:${C.onDarkMuted};">${bandLine}</p>` : ''}
</td></tr>
<tr><td height="4" bgcolor="${C.gold}" style="background-color:${C.gold};height:4px;line-height:4px;font-size:0;">&nbsp;</td></tr>
<tr><td bgcolor="${C.paper}" style="background-color:${C.paper};border:1px solid ${C.edge};border-top:0;padding:32px 26px 30px 26px;">
${body}
</td></tr>
<tr><td align="center" style="padding:22px 16px 0 16px;font-family:${SANS};font-size:13px;line-height:1.6;color:${C.muted};">
${footer}
</td></tr>
</table>
</td></tr></table>
</body></html>
`;
}

function contactFooter(ctx: EmailContext, extra = ''): string {
  const name = escapeHtml(ctx.businessName || 'MAS Monograms');
  const place = [ctx.city, ctx.state]
    .filter((v): v is string => !!v)
    .map((v) => escapeHtml(v))
    .join(', ');
  const lines = [
    `<strong style="font-family:${SERIF};font-size:15px;font-weight:normal;color:${C.midnight};">${name}</strong>${place ? `, ${place}` : ''}`,
  ];
  const reach: string[] = [link(SITE_URL, 'mas-monograms.com')];
  if (ctx.email) reach.push(link(`mailto:${escapeHtml(ctx.email)}`, escapeHtml(ctx.email)));
  const tel = ctx.phone ? telHref(ctx.phone) : null;
  if (ctx.phone && tel) reach.push(link(escapeHtml(tel), escapeHtml(ctx.phone)));
  lines.push(reach.join(' &nbsp;&middot;&nbsp; '));
  if (extra) lines.push(extra);
  return lines.map((l) => `<p style="margin:0 0 4px 0;">${l}</p>`).join('');
}

function contactText(ctx: EmailContext): string {
  const place = [ctx.city, ctx.state].filter(Boolean).join(', ');
  return [
    `${ctx.businessName || 'MAS Monograms'}${place ? `, ${place}` : ''}`,
    [SITE_URL, ctx.email, ctx.phone].filter(Boolean).join(' | '),
  ].join('\n');
}

/** Plain-text label/value block. */
function textBlock(
  title: string,
  rows: Array<[string, string | null | undefined | false]>,
): string {
  const kept = rows.filter(([, v]) => v) as Array<[string, string]>;
  if (!kept.length) return '';
  return `${title.toUpperCase()}\n${kept.map(([l, v]) => `${l}: ${v.replace(/\r?\n/g, '\n  ')}`).join('\n')}`;
}

/** The monogram panel: initials set large when the prefill supplied them. */
function monogramPanel(s: QuoteSubmission, initials: string | null, fabric: string | null): string {
  const meta = [s.monogramStyle, s.threadColor && `${s.threadColor} thread`, fabric]
    .filter(Boolean)
    .map((v) => escapeHtml(v as string))
    .join(' &nbsp;&middot;&nbsp; ');
  const big = initials
    ? `<p style="margin:0 0 6px 0;font-family:${SERIF};font-size:44px;line-height:1.1;letter-spacing:0.12em;color:${C.midnight};">${escapeHtml(initials)}</p>`
    : `<p style="margin:0 0 8px 0;font-family:${SERIF};font-size:19px;line-height:1.45;color:${C.midnight};word-break:break-word;overflow-wrap:anywhere;">${escLines(s.personalization)}</p>`;
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:6px 0 4px 0;"><tr><td align="center" bgcolor="${C.well}" style="background-color:${C.well};border:2px dashed ${C.brass};border-radius:10px;padding:22px 18px;">${big}${meta ? `<p style="margin:0;font-family:${SANS};font-size:14px;line-height:1.5;color:${C.muted};">${meta}</p>` : ''}</td></tr></table>`;
}

// ── Customer confirmation ──────────────────────────────────────────────────────
export function buildCustomerEmail(s: QuoteSubmission, ctx: EmailContext = {}): BuiltEmail {
  const first = firstName(s.name);
  const initials = parseInitials(s.personalization);
  const fabric = parseFabric(s.itemDescription);
  const steps = ctx.nextSteps?.filter(Boolean).length ? ctx.nextSteps! : FALLBACK_NEXT_STEPS;
  const stepsLabel = ctx.nextStepsLabel || "What's next";
  const contactLine = [
    ctx.email ? link(`mailto:${escapeHtml(ctx.email)}`, escapeHtml(ctx.email)) : '',
    ctx.phone && telHref(ctx.phone)
      ? link(escapeHtml(telHref(ctx.phone)!), escapeHtml(ctx.phone))
      : '',
  ]
    .filter(Boolean)
    .join(' or ');

  const item = `${escapeHtml(s.itemType)}${s.quantity ? ` (${escapeHtml(s.quantity)})` : ''}`;
  const summary = details([
    ['Item', item],
    ['Your own item?', escapeHtml(s.ownership)],
    ['About the item', s.itemDescription && escLines(s.itemDescription)],
    ['Personalization', initials ? escLines(s.personalization) : null],
    ['Style', escapeHtml(s.monogramStyle)],
    ['Placement', escapeHtml(s.placement)],
    ['Size', escapeHtml(s.size)],
    ['Thread colors', escapeHtml(s.threadCount)],
    ['Font', s.fontPreference && escapeHtml(s.fontPreference)],
    ['Thread color', s.threadColor && escapeHtml(s.threadColor)],
    ['Needed by', s.neededBy && escapeHtml(formatNeededBy(s.neededBy))],
    ['Gift', s.isGift ? 'Yes' : null],
    [
      'Rush',
      s.isRush ? `<strong style="color:${C.claret};">Yes, a rush fee may apply</strong>` : null,
    ],
    ['Photos', s.attachmentNames.length ? escapeHtml(s.attachmentNames.join(', ')) : null],
  ]);

  const stepRows = steps
    .map(
      (step, i) =>
        `<tr><td valign="top" width="40" style="padding:0 12px 14px 0;"><table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" width="30" height="30" style="width:30px;height:30px;border:2px solid ${C.gold};border-radius:999px;font-family:${SERIF};font-size:15px;line-height:30px;color:${C.midnight};">${i + 1}</td></tr></table></td><td valign="top" style="padding:5px 0 14px 0;font-family:${SANS};font-size:15px;line-height:1.55;color:${C.ink};">${escapeHtml(step)}</td></tr>`,
    )
    .join('');

  const body = [
    h1(`Thank you, ${escapeHtml(first)}.`),
    para(
      "Your quote request is in, and it's on its way to my inbox. I read every one personally, and I'll be in touch within 1 business day to discuss your order.",
    ),
    monogramPanel(s, initials, fabric),
    stitch(26, 22),
    h2('What you asked for'),
    summary,
    stitch(24, 22),
    h2(escapeHtml(stepsLabel)),
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">${stepRows}</table>`,
    para(
      'Nothing is stitched and nothing is charged until you approve your quote.',
      `color:${C.muted};font-size:15px;`,
    ),
    stitch(10, 22),
    para(
      contactLine
        ? `Questions in the meantime? You can reach me at ${contactLine}.`
        : `Questions in the meantime? You can reach me through ${link(SITE_URL, 'mas-monograms.com')}.`,
    ),
    `<p style="margin:18px 0 0 0;font-family:${SERIF};font-size:22px;font-style:italic;line-height:1.3;color:${C.midnight};">Mary Ann</p>`,
    `<p style="margin:2px 0 0 0;font-family:${SANS};font-size:13px;line-height:1.4;color:${C.muted};">${escapeHtml(ctx.businessName || 'MAS Monograms')}</p>`,
  ].join('\n');

  const html = shell({
    title: 'We got your quote request',
    preheader: `Thanks, ${escapeHtml(first)}. I'll be in touch within 1 business day.`,
    body,
    footer: contactFooter(
      ctx,
      'You are getting this because you asked for a quote on our website.',
    ),
  });

  const text = [
    'MAS Monograms',
    '',
    `Thank you, ${first}.`,
    '',
    "Your quote request is in, and it's on its way to my inbox. I read every one personally, and I'll be in touch within 1 business day to discuss your order.",
    '',
    textBlock('What you asked for', [
      ['Item', `${s.itemType}${s.quantity ? ` (${s.quantity})` : ''}`],
      ['Your own item?', s.ownership],
      ['About the item', s.itemDescription],
      ['Personalization', s.personalization],
      ['Style', s.monogramStyle],
      ['Placement', s.placement],
      ['Size', s.size],
      ['Thread colors', s.threadCount],
      ['Font', s.fontPreference],
      ['Thread color', s.threadColor],
      ['Needed by', s.neededBy && formatNeededBy(s.neededBy)],
      ['Gift', s.isGift ? 'Yes' : null],
      ['Rush', s.isRush ? 'Yes, a rush fee may apply' : null],
      ['Photos', s.attachmentNames.join(', ')],
    ]),
    '',
    stepsLabel.toUpperCase(),
    ...steps.map((step, i) => `${i + 1}. ${step}`),
    '',
    'Nothing is stitched and nothing is charged until you approve your quote.',
    '',
    `Questions in the meantime? ${[ctx.email, ctx.phone].filter(Boolean).join(' or ') || SITE_URL}`,
    '',
    'Mary Ann',
    '',
    '---',
    contactText(ctx),
  ].join('\n');

  return { subject: 'We got your quote request! | MAS Monograms', html, text };
}

// ── Owner notification ─────────────────────────────────────────────────────────
export function buildOwnerEmail(s: QuoteSubmission, ctx: EmailContext = {}): BuiltEmail {
  const when = s.submittedAt.toLocaleString('en-US', {
    timeZone: 'America/New_York',
    dateStyle: 'medium',
    timeStyle: 'short',
  });
  const initials = parseInitials(s.personalization);
  const fabric = parseFabric(s.itemDescription);
  const eEmail = escapeHtml(s.email);
  const tel = s.phone ? telHref(s.phone) : null;
  const replyHref = escapeHtml(
    `mailto:${s.email}?subject=${encodeURIComponent('Your MAS Monograms quote')}`,
  );
  const item = `${escapeHtml(s.itemType)}${s.quantity ? ` (${escapeHtml(s.quantity)})` : ''}`;
  // "QR code on a hang tag or label (campaign fall-fair)"; null (row hidden) with no tags.
  const foundVia = describeUtm(s.utm);

  const actions = `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:6px 0 8px 0;"><tr><td style="padding:0 0 12px 0;">${button(replyHref, 'Reply by email')}</td></tr>${tel ? `<tr><td style="padding:0 0 12px 4px;font-family:${SANS};font-size:16px;line-height:1.3;">${link(escapeHtml(tel), `Call ${escapeHtml(s.phone)}`)}</td></tr>` : ''}</table>`;

  const keyFacts = details([
    [
      'Needed by',
      s.neededBy
        ? `<strong style="color:${C.midnight};">${escapeHtml(formatNeededBy(s.neededBy))}</strong>`
        : 'No date given',
    ],
    ['Rush?', s.isRush ? `<strong style="color:${C.claret};">Yes, rush requested</strong>` : 'No'],
    ['Gift?', s.isGift ? 'Yes' : 'No'],
  ]);

  const section = (title: string, rows: Array<[string, string | null | undefined | false]>) => {
    const t = details(rows);
    return t ? `${stitch(22, 18)}${h2(title)}${t}` : '';
  };

  const body = [
    s.isRush ? rushBadge('RUSH REQUESTED') : '',
    h1(escapeHtml(s.name)),
    para(
      `would like a quote for <strong style="color:${C.midnight};">${item}</strong>.`,
      'margin-top:-6px;',
    ),
    actions,
    keyFacts,
    section('Contact', [
      ['Name', escapeHtml(s.name)],
      ['Email', link(`mailto:${eEmail}`, eEmail)],
      [
        'Phone',
        s.phone
          ? tel
            ? link(escapeHtml(tel), escapeHtml(s.phone))
            : escapeHtml(s.phone)
          : 'Not given',
      ],
      ['Heard about us', s.referral && escapeHtml(s.referral)],
      ['Where they found you', foundVia && escapeHtml(foundVia)],
    ]),
    section('Item', [
      ['Item type', escapeHtml(s.itemType)],
      ['Owns the item?', escapeHtml(s.ownership)],
      ['Description', s.itemDescription && escLines(s.itemDescription)],
      ['Quantity', s.quantity && escapeHtml(s.quantity)],
    ]),
    `${stitch(22, 18)}${h2('Monogram')}`,
    monogramPanel(s, initials, fabric),
    `<div style="height:10px;line-height:10px;font-size:0;">&nbsp;</div>`,
    details([
      ['Personalization', escLines(s.personalization)],
      ['Style', escapeHtml(s.monogramStyle)],
      ['Placement', escapeHtml(s.placement)],
      ['Size', escapeHtml(s.size)],
      ['Thread colors', escapeHtml(s.threadCount)],
      ['Font', s.fontPreference && escapeHtml(s.fontPreference)],
      ['Thread color', s.threadColor && escapeHtml(s.threadColor)],
    ]),
    s.notes ? `${stitch(22, 18)}${h2('Notes')}${para(escLines(s.notes))}` : '',
    s.attachmentNames.length
      ? section('Photos attached', [['Files', escapeHtml(s.attachmentNames.join(', '))]])
      : '',
    stitch(22, 14),
    `<p style="margin:0;font-family:${SANS};font-size:12px;line-height:1.5;color:${C.muted};">Reply to this email to answer ${escapeHtml(firstName(s.name))} directly. Received ${escapeHtml(when)}. Submission ID ${escapeHtml(s.submissionId)}</p>`,
  ].join('\n');

  const html = shell({
    title: 'New quote request',
    preheader: `${s.isRush ? 'RUSH. ' : ''}${escapeHtml(s.name)}: ${item}${s.neededBy ? `, needed by ${escapeHtml(formatNeededBy(s.neededBy))}` : ''}`,
    bandLine: 'New quote request',
    body,
    footer: contactFooter(ctx),
  });

  const text = [
    'MAS Monograms: new quote request',
    '',
    s.isRush ? '*** RUSH REQUESTED ***\n' : '',
    `${s.name} would like a quote for ${s.itemType}${s.quantity ? ` (${s.quantity})` : ''}.`,
    `Needed by: ${s.neededBy ? formatNeededBy(s.neededBy) : 'No date given'}`,
    `Reply: ${s.email}${s.phone ? `  |  Call: ${s.phone}` : ''}`,
    '',
    textBlock('Contact', [
      ['Name', s.name],
      ['Email', s.email],
      ['Phone', s.phone || 'Not given'],
      ['Heard about us', s.referral],
      ['Where they found you', foundVia],
    ]),
    '',
    textBlock('Item', [
      ['Item type', s.itemType],
      ['Owns the item?', s.ownership],
      ['Description', s.itemDescription],
      ['Quantity', s.quantity],
    ]),
    '',
    textBlock('Monogram', [
      ['Personalization', s.personalization],
      ['Style', s.monogramStyle],
      ['Placement', s.placement],
      ['Size', s.size],
      ['Thread colors', s.threadCount],
      ['Font', s.fontPreference],
      ['Thread color', s.threadColor],
    ]),
    '',
    textBlock('Logistics', [
      ['Needed by', s.neededBy && formatNeededBy(s.neededBy)],
      ['Rush?', s.isRush ? 'Yes, rush requested' : 'No'],
      ['Gift?', s.isGift ? 'Yes' : 'No'],
    ]),
    s.notes ? `\nNOTES\n${s.notes}` : '',
    s.attachmentNames.length ? `\nPHOTOS ATTACHED\n${s.attachmentNames.join(', ')}` : '',
    '',
    `Received ${when}. Submission ID ${s.submissionId}`,
  ]
    .filter((line, i, all) => !(line === '' && all[i - 1] === ''))
    .join('\n');

  return { subject: `New Quote Request from ${s.name}`, html, text };
}
