/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type StudioPlaybook = {
  _id: string;
  _type: 'studioPlaybook';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  guides?: Array<{
    title?: string;
    summary?: string;
    sections?: Array<{
      heading?: string;
      tone?: 'default' | 'primary' | 'positive' | 'caution';
      body?: string;
      bullets?: Array<string>;
      links?: Array<{
        label?: string;
        url?: string;
        _type: 'playbookLink';
        _key: string;
      }>;
      _type: 'playbookSection';
      _key: string;
    }>;
    _type: 'playbookGuide';
    _key: string;
  }>;
};

export type StudioNotes = {
  _id: string;
  _type: 'studioNotes';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessSummary?: string;
  idealClient?: string;
  voiceSummary?: string;
  wordsToAvoid?: Array<string>;
};

export type StudioGuide = {
  _id: string;
  _type: 'studioGuide';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guideTitle?: string;
  guideIntro?: string;
  studioMap?: Array<{
    area?: string;
    description?: string;
    _type: 'mapRow';
    _key: string;
  }>;
  howTos?: Array<{
    title?: string;
    steps?: Array<string>;
    _type: 'howTo';
    _key: string;
  }>;
  tips?: Array<{
    heading?: string;
    tone?: 'default' | 'primary' | 'caution' | 'positive';
    body?: string;
    _type: 'tip';
    _key: string;
  }>;
};

export type LegalPage = {
  _id: string;
  _type: 'legalPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seoDescription?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3';
    listItem?: 'bullet';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  displayOrder?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type FaqItem = {
  _id: string;
  _type: 'faqItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h4';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  category?: 'Ordering' | 'Pricing' | 'Turnaround' | 'Shipping' | 'Items' | 'Design' | 'Care';
  displayOrder?: number;
  showOnHowItWorks?: boolean;
  showOnPricing?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ClearanceItem = {
  _id: string;
  _type: 'clearanceItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  originalPrice?: number;
  salePrice?: number;
  stripePaymentLink?: string;
  quantityAvailable?: number;
  sold?: boolean;
  featured?: boolean;
  displayOrder?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PricingTier = {
  _id: string;
  _type: 'pricingTier';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  minQuantity?: number;
  maxQuantity?: number;
  pricePerPiece?: number;
  note?: string;
  highlighted?: boolean;
  displayOrder?: number;
};

export type ItemCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'itemCategory';
};

export type FontReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'font';
};

export type GalleryItem = {
  _id: string;
  _type: 'galleryItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  relatedCategory?: ItemCategoryReference;
  relatedFont?: FontReference;
  tags?: Array<string>;
  featured?: boolean;
  displayOrder?: number;
};

export type ThreadColor = {
  _id: string;
  _type: 'threadColor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  hexColor?: string;
  dmcNumber?: string;
  swatchImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  colorFamily?:
    | 'blue'
    | 'green'
    | 'red'
    | 'orange'
    | 'purple'
    | 'brown'
    | 'gray'
    | 'white'
    | 'metallic';
  displayOrder?: number;
};

export type Font = {
  _id: string;
  _type: 'font';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  previewImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  styleTag?: 'classic' | 'script' | 'block' | 'modern' | 'monogram';
  description?: string;
  bestFor?: Array<string>;
  popular?: boolean;
  displayOrder?: number;
};

export type ItemCategory = {
  _id: string;
  _type: 'itemCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  eyebrow?: string;
  description?: string;
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  cardImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  trustItems?: Array<string>;
  startingPrice?: string;
  ctaLabel?: string;
  displayOrder?: number;
  featured?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type NotFoundPage = {
  _id: string;
  _type: 'notFoundPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  headline?: string;
  body?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
};

export type ThankYouPage = {
  _id: string;
  _type: 'thankYouPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  eyebrow?: string;
  headline?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  expectedResponseTime?: string;
  nextSteps?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  ctaLabel?: string;
  ctaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
};

export type ClearancePage = {
  _id: string;
  _type: 'clearancePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  paymentNote?: string;
  pickupNote?: string;
  soldOutLabel?: string;
  buyButtonLabel?: string;
  emptyStateMessage?: string;
  emptyStateCtaLabel?: string;
  emptyStateCtaHref?: string;
  emptyStateSecondaryLabel?: string;
  emptyStateSecondaryHref?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type ThreadChartPage = {
  _id: string;
  _type: 'threadChartPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  matchingNote?: string;
  customColorNote?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type FontGuidePage = {
  _id: string;
  _type: 'fontGuidePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h3';
    listItem?: 'bullet';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  fontGridEyebrow?: string;
  fontGridHeadline?: string;
  customFontNote?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type StyleGalleryPage = {
  _id: string;
  _type: 'styleGalleryPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  filterAllLabel?: string;
  additionalFilterTags?: Array<{
    label?: string;
    tag?: string;
    _type: 'filterTag';
    _key: string;
  }>;
  filterGroups?: Array<{
    groupLabel?: string;
    tags?: Array<string>;
    _type: 'filterGroup';
    _key: string;
  }>;
  emptyStateMessage?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type ShopIndexPage = {
  _id: string;
  _type: 'shopIndexPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  gridIntro?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type RequestAQuotePage = {
  _id: string;
  _type: 'requestAQuotePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  heroTrustItems?: Array<string>;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  turnaroundCallout?: string;
  nameLabel?: string;
  namePlaceholder?: string;
  emailLabel?: string;
  emailPlaceholder?: string;
  emailHelp?: string;
  phoneLabel?: string;
  phonePlaceholder?: string;
  phoneHelp?: string;
  itemTypeLabel?: string;
  itemTypeHelp?: string;
  itemTypeOtherLabel?: string;
  ownershipLabel?: string;
  ownershipHelp?: string;
  itemDescriptionLabel?: string;
  itemDescriptionPlaceholder?: string;
  itemDescriptionHelp?: string;
  monogramStyleLabel?: string;
  monogramStyleHelp?: string;
  placementSelectLabel?: string;
  placementSelectHelp?: string;
  sizeLabel?: string;
  sizeHelp?: string;
  threadCountLabel?: string;
  threadCountHelp?: string;
  quantityLabel?: string;
  quantityPlaceholder?: string;
  quantityHelp?: string;
  monogramDetailsLabel?: string;
  monogramDetailsPlaceholder?: string;
  monogramDetailsHelp?: string;
  placementLabel?: string;
  placementPlaceholder?: string;
  placementHelp?: string;
  fontPreferenceLabel?: string;
  fontPreferenceHelp?: string;
  fontPreferenceGuideLinkLabel?: string;
  fontPreferenceOtherLabel?: string;
  colorPreferenceLabel?: string;
  colorPreferencePlaceholder?: string;
  colorPreferenceHelp?: string;
  colorPreferenceChartLinkLabel?: string;
  fileUploadLabel?: string;
  fileUploadHelp?: string;
  fileUploadAcceptedTypes?: string;
  rushLabel?: string;
  rushHelp?: string;
  neededByLabel?: string;
  neededByHelp?: string;
  specialInstructionsLabel?: string;
  specialInstructionsPlaceholder?: string;
  specialInstructionsHelp?: string;
  referralLabel?: string;
  referralOptions?: Array<string>;
  submitLabel?: string;
  privacyNote?: string;
  errorMessage?: string;
  requiredFieldNote?: string;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  storyHeadline?: string;
  storyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  makerPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  makerAttribution?: string;
  studioNote?: string;
  recentWorkHeadline?: string;
  valuesHeadline?: string;
  values?: Array<{
    label?: string;
    body?: string;
    _type: 'valueItem';
    _key: string;
  }>;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type PricingPage = {
  _id: string;
  _type: 'pricingPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  tiersHeadline?: string;
  tiersSubhead?: string;
  addonsHeadline?: string;
  addons?: Array<{
    label?: string;
    price?: string;
    note?: string;
    _type: 'addon';
    _key: string;
  }>;
  rushHeadline?: string;
  rushBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  faqHeadline?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type HowItWorksPage = {
  _id: string;
  _type: 'howItWorksPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  stepsHeadline?: string;
  stepsSubhead?: string;
  steps?: Array<{
    number?: string;
    label?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: null;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    _type: 'step';
    _key: string;
  }>;
  faqHeadline?: string;
  faqSubhead?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroItalicWord?: string;
  heroSubhead?: string;
  heroPrimaryCtaLabel?: string;
  heroPrimaryCtaHref?: string;
  heroSecondaryCtaLabel?: string;
  heroSecondaryCtaHref?: string;
  trustItems?: Array<string>;
  categoriesEyebrow?: string;
  categoriesHeadline?: string;
  categoriesSubhead?: string;
  aboutEyebrow?: string;
  aboutHeadline?: string;
  aboutBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  aboutPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  aboutCtaLabel?: string;
  aboutCtaHref?: string;
  processEyebrow?: string;
  processHeadline?: string;
  processSubhead?: string;
  processSteps?: Array<{
    number?: string;
    label?: string;
    body?: string;
    _type: 'processStep';
    _key: string;
  }>;
  processCtaLabel?: string;
  processCtaHref?: string;
  galleryEyebrow?: string;
  galleryHeadline?: string;
  gallerySubhead?: string;
  galleryCtaLabel?: string;
  galleryCtaHref?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  email?: string;
  phone?: string;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
  };
  serviceArea?: string;
  geo?: {
    latitude?: number;
    longitude?: number;
  };
  openingHours?: Array<{
    days?: Array<string>;
    opens?: string;
    closes?: string;
    _type: 'hoursSpec';
    _key: string;
  }>;
  navItems?: Array<
    | {
        label?: string;
        href?: string;
        _type: 'navLink';
        _key: string;
      }
    | {
        label?: string;
        links?: Array<{
          label?: string;
          href?: string;
          _type: 'navSubLink';
          _key: string;
        }>;
        _type: 'navGroup';
        _key: string;
      }
  >;
  quoteCtaLabel?: string;
  footerColumns?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _type: 'footerLink';
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }>;
  socialLinks?: Array<{
    platform?: 'Facebook' | 'Instagram' | 'Pinterest' | 'TikTok' | 'YouTube' | 'Other';
    url?: string;
    label?: string;
    _type: 'socialLink';
    _key: string;
  }>;
  googleBusinessUrl?: string;
  footerCredit?: string;
  footerCreditUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  businessType?: 'LocalBusiness' | 'Store' | 'ProfessionalService' | 'ClothingStore';
  priceRange?: '$' | '$$' | '$$$';
  standardTurnaround?: string;
  rushOrdersAvailable?: boolean;
  rushTurnaround?: string;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | StudioPlaybook
  | StudioNotes
  | StudioGuide
  | LegalPage
  | Slug
  | FaqItem
  | SanityImageAssetReference
  | ClearanceItem
  | SanityImageCrop
  | SanityImageHotspot
  | PricingTier
  | ItemCategoryReference
  | FontReference
  | GalleryItem
  | ThreadColor
  | Font
  | ItemCategory
  | NotFoundPage
  | ThankYouPage
  | ClearancePage
  | ThreadChartPage
  | FontGuidePage
  | StyleGalleryPage
  | ShopIndexPage
  | RequestAQuotePage
  | AboutPage
  | PricingPage
  | HowItWorksPage
  | HomePage
  | SiteSettings
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
