/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TrashedItem = {
  _id: string;
  _type: 'trashedItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  kind?: string;
  deletedAt?: string;
  wasPublished?: boolean;
  originalType?: string;
  originalId?: string;
  payload?: string;
};

export type StudioPlaybook = {
  _id: string;
  _type: 'studioPlaybook';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  guides?: Array<{
    title?: string;
    summary?: string;
    sections?: Array<{
      heading?: string;
      tone?: 'default' | 'primary' | 'positive' | 'caution';
      body?: string;
      bullets?: Array<string>;
      links?: Array<{
        label?: string;
        url?: string;
        _type: 'playbookLink';
        _key: string;
      }>;
      _type: 'playbookSection';
      _key: string;
    }>;
    _type: 'playbookGuide';
    _key: string;
  }>;
};

export type StudioNotes = {
  _id: string;
  _type: 'studioNotes';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessSummary?: string;
  idealClient?: string;
  voiceSummary?: string;
  wordsToAvoid?: Array<string>;
  helpContact?: string;
};

export type StudioGuide = {
  _id: string;
  _type: 'studioGuide';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guideTitle?: string;
  guideIntro?: string;
  videoUrl?: string;
  videoLabel?: string;
  studioMap?: Array<{
    area?: string;
    description?: string;
    _type: 'mapRow';
    _key: string;
  }>;
  howTos?: Array<{
    title?: string;
    steps?: Array<string>;
    _type: 'howTo';
    _key: string;
  }>;
  tips?: Array<{
    heading?: string;
    tone?: 'default' | 'primary' | 'caution' | 'positive';
    body?: string;
    _type: 'tip';
    _key: string;
  }>;
};

export type FaqItem = {
  _id: string;
  _type: 'faqItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h4';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  showOnHowItWorks?: boolean;
  showOnPricing?: boolean;
  category?: 'Ordering' | 'Pricing' | 'Turnaround' | 'Shipping' | 'Items' | 'Design' | 'Care';
  displayOrder?: number;
  orderRank?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ClearanceItem = {
  _id: string;
  _type: 'clearanceItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  sold?: boolean;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  description?: string;
  salePrice?: number;
  originalPrice?: number;
  stripePaymentLink?: string;
  quantityAvailable?: number;
  displayOrder?: number;
  orderRank?: string;
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PricingTier = {
  _id: string;
  _type: 'pricingTier';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  pricePerPiece?: number;
  note?: string;
  highlighted?: boolean;
  highlightLabel?: string;
  displayOrder?: number;
  orderRank?: string;
  minQuantity?: number;
  maxQuantity?: number;
};

export type ItemCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'itemCategory';
};

export type FontReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'font';
};

export type GalleryItem = {
  _id: string;
  _type: 'galleryItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  relatedCategory?: ItemCategoryReference;
  relatedFont?: FontReference;
  tags?: Array<string>;
  featured?: boolean;
  hoopFit?: 'good' | 'poor';
  displayOrder?: number;
  orderRank?: string;
};

export type ThreadColor = {
  _id: string;
  _type: 'threadColor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  hexColor?: string;
  colorFamily?:
    'blue' | 'green' | 'red' | 'orange' | 'purple' | 'brown' | 'gray' | 'white' | 'metallic';
  dmcNumber?: string;
  displayOrder?: number;
  slug?: Slug;
  swatchImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Font = {
  _id: string;
  _type: 'font';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  previewImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  styleTag?: 'classic' | 'script' | 'block' | 'modern' | 'monogram';
  description?: string;
  bestFor?: Array<string>;
  popular?: boolean;
  atelierStyle?: 'classic' | 'script' | 'block' | 'circle' | 'single';
  displayOrder?: number;
  orderRank?: string;
  slug?: Slug;
};

export type NotFoundPage = {
  _id: string;
  _type: 'notFoundPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  seoTitle?: string;
  seoDescription?: string;
  body?: string;
};

export type AtelierSettings = {
  _id: string;
  _type: 'atelierSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  initialsLabel?: string;
  initialsHint?: string;
  styleLabel?: string;
  threadLabel?: string;
  fabricLabel?: string;
  styles?: Array<{
    key?: 'classic' | 'script' | 'block' | 'circle' | 'single';
    label?: string;
    blurb?: string;
    _type: 'atelierStyle';
    _key: string;
  }>;
  fabrics?: Array<{
    key?: string;
    label?: string;
    color?: string;
    note?: string;
    _type: 'atelierFabric';
    _key: string;
  }>;
  replayLabel?: string;
  ctaLabel?: string;
  disclaimer?: string;
  pauseLabel?: string;
  playLabel?: string;
  sampleMonograms?: Array<string>;
  heroTryLabel?: string;
  heroPlaceholder?: string;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  phone?: string;
  email?: string;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
  };
  serviceArea?: string;
  openingHours?: Array<{
    days?: Array<string>;
    opens?: string;
    closes?: string;
    _type: 'hoursSpec';
    _key: string;
  }>;
  socialLinks?: Array<{
    platform?: 'Facebook' | 'Instagram' | 'Pinterest' | 'TikTok' | 'YouTube' | 'Nextdoor' | 'Other';
    url?: string;
    label?: string;
    _type: 'socialLink';
    _key: string;
  }>;
  googleReviewUrl?: string;
  reviewLinkLabel?: string;
  googleBusinessUrl?: string;
  tagline?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  navItems?: Array<
    | ({
        _key: string;
      } & NavLink)
    | {
        label?: string;
        links?: Array<
          | ({
              _key: string;
            } & NavLink)
          | {
              label?: string;
              href?: string;
              _type: 'navSubLink';
              _key: string;
            }
        >;
        _type: 'navGroup';
        _key: string;
      }
  >;
  headerCta?: {
    show?: boolean;
    label?: string;
    link?: NavLink;
  };
  quoteCtaLabel?: string;
  menuContactLabel?: string;
  showEmail?: boolean;
  showSocials?: boolean;
  footerColumns?: Array<{
    title?: string;
    links?: Array<
      | ({
          _key: string;
        } & NavLink)
      | {
          label?: string;
          href?: string;
          _type: 'footerLink';
          _key: string;
        }
    >;
    _type: 'footerColumn';
    _key: string;
  }>;
  legalNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  showFooterSocials?: boolean;
  footerCredit?: string;
  footerCreditUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  businessType?: 'LocalBusiness' | 'Store' | 'ProfessionalService' | 'ClothingStore';
  priceRange?: '$' | '$$' | '$$$';
  geo?: {
    latitude?: number;
    longitude?: number;
  };
  standardTurnaround?: string;
  rushOrdersAvailable?: boolean;
  rushTurnaround?: string;
};

export type HomePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'homePage';
};

export type HowItWorksPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'howItWorksPage';
};

export type PricingPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'pricingPage';
};

export type AboutPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'aboutPage';
};

export type RequestAQuotePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'requestAQuotePage';
};

export type ShopIndexPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'shopIndexPage';
};

export type StyleGalleryPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'styleGalleryPage';
};

export type FontGuidePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'fontGuidePage';
};

export type ThreadChartPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'threadChartPage';
};

export type ClearancePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'clearancePage';
};

export type ThankYouPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'thankYouPage';
};

export type LegalPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'legalPage';
};

export type NavLink = {
  _type: 'navLink';
  label?: string;
  linkType?: 'internal' | 'external' | 'custom';
  internalPage?:
    | HomePageReference
    | HowItWorksPageReference
    | PricingPageReference
    | AboutPageReference
    | RequestAQuotePageReference
    | ShopIndexPageReference
    | StyleGalleryPageReference
    | FontGuidePageReference
    | ThreadChartPageReference
    | ClearancePageReference
    | ThankYouPageReference
    | ItemCategoryReference
    | LegalPageReference;
  externalUrl?: string;
  href?: string;
};

export type LegalPage = {
  _id: string;
  _type: 'legalPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3';
    listItem?: 'bullet';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  lastUpdated?: string;
  lastUpdatedLabel?: string;
  slug?: Slug;
  displayOrder?: number;
  seoPreview?: string;
  seoDescription?: string;
};

export type ItemCategory = {
  _id: string;
  _type: 'itemCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  eyebrow?: string;
  description?: string;
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  trustItems?: Array<string>;
  cardImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  startingPrice?: string;
  displayOrder?: number;
  orderRank?: string;
  ctaLabel?: string;
  galleryHeading?: string;
  requestSimilarLabel?: string;
  crossSellHeading?: string;
  bannerEyebrow?: string;
  bannerHeadline?: string;
  bannerSubhead?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  featured?: boolean;
};

export type ThankYouPage = {
  _id: string;
  _type: 'thankYouPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  responseTimeLabel?: string;
  expectedResponseTime?: string;
  nextStepsLabel?: string;
  nextSteps?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  ctaLabel?: string;
  ctaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  seoTitle?: string;
};

export type ClearancePage = {
  _id: string;
  _type: 'clearancePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  paymentNote?: string;
  pickupNote?: string;
  buyButtonLabel?: string;
  soldOutLabel?: string;
  quantityLeftLabel?: string;
  emptyStateMessage?: string;
  emptyStateCtaLabel?: string;
  emptyStateCtaHref?: string;
  emptyStateSecondaryLabel?: string;
  emptyStateSecondaryHref?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type ThreadChartPage = {
  _id: string;
  _type: 'threadChartPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  filterLabel?: string;
  matchingNote?: string;
  customColorNote?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type FontGuidePage = {
  _id: string;
  _type: 'fontGuidePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h3';
    listItem?: 'bullet';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  fontGridEyebrow?: string;
  fontGridHeadline?: string;
  popularLabel?: string;
  tryItLabel?: string;
  customFontNote?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type StyleGalleryPage = {
  _id: string;
  _type: 'styleGalleryPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  introCtaLabel?: string;
  filterGroups?: Array<{
    groupLabel?: string;
    tags?: Array<string>;
    _type: 'filterGroup';
    _key: string;
  }>;
  filterAllLabel?: string;
  filterToggleLabel?: string;
  moreTagsLabel?: string;
  lessTagsLabel?: string;
  filterFallbackHeading?: string;
  emptyStateMessage?: string;
  filterGroupName?: string;
  resultsAnnouncement?: string;
  requestLabel?: string;
  fontCaption?: string;
  lightboxLabel?: string;
  lightboxCloseLabel?: string;
  lightboxPrevLabel?: string;
  lightboxNextLabel?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  additionalFilterTags?: Array<{
    label?: string;
    tag?: string;
    _type: 'filterTag';
    _key: string;
  }>;
};

export type ShopIndexPage = {
  _id: string;
  _type: 'shopIndexPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  gridIntro?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type RequestAQuotePage = {
  _id: string;
  _type: 'requestAQuotePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  heroTrustItems?: Array<string>;
  turnaroundCallout?: string;
  requiredFieldNote?: string;
  orderInfoHeading?: string;
  itemTypeLabel?: string;
  itemTypeHelp?: string;
  ownershipLabel?: string;
  ownershipHelp?: string;
  itemDescriptionLabel?: string;
  itemDescriptionPlaceholder?: string;
  itemDescriptionHelp?: string;
  monogramStyleLabel?: string;
  monogramStyleHelp?: string;
  placementSelectLabel?: string;
  placementSelectHelp?: string;
  sizeLabel?: string;
  sizeHelp?: string;
  threadCountLabel?: string;
  threadCountHelp?: string;
  quantityLabel?: string;
  quantityPlaceholder?: string;
  quantityHelp?: string;
  fontPreferenceLabel?: string;
  fontPreferenceHelp?: string;
  neededByLabel?: string;
  neededByHelp?: string;
  rushLabel?: string;
  rushHelp?: string;
  personalInfoHeading?: string;
  nameLabel?: string;
  namePlaceholder?: string;
  emailLabel?: string;
  emailPlaceholder?: string;
  phoneLabel?: string;
  phonePlaceholder?: string;
  referralLabel?: string;
  referralOptions?: Array<string>;
  attachmentsHeading?: string;
  additionalHeading?: string;
  submitLabel?: string;
  privacyNote?: string;
  noScriptMessage?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  emailHelp?: string;
  phoneHelp?: string;
  itemTypeOtherLabel?: string;
  monogramDetailsLabel?: string;
  monogramDetailsPlaceholder?: string;
  monogramDetailsHelp?: string;
  placementLabel?: string;
  placementPlaceholder?: string;
  placementHelp?: string;
  fontPreferenceGuideLinkLabel?: string;
  fontPreferenceOtherLabel?: string;
  colorPreferenceLabel?: string;
  colorPreferencePlaceholder?: string;
  colorPreferenceHelp?: string;
  colorPreferenceChartLinkLabel?: string;
  fileUploadLabel?: string;
  fileUploadHelp?: string;
  fileUploadAcceptedTypes?: string;
  specialInstructionsLabel?: string;
  specialInstructionsPlaceholder?: string;
  specialInstructionsHelp?: string;
  errorMessage?: string;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  makerPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  makerAttribution?: string;
  storyHeadline?: string;
  storyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  studioNote?: string;
  recentWorkHeadline?: string;
  valuesHeadline?: string;
  values?: Array<{
    label?: string;
    body?: string;
    _type: 'valueItem';
    _key: string;
  }>;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type PricingPage = {
  _id: string;
  _type: 'pricingPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  tiersHeadline?: string;
  tiersSubhead?: string;
  tierPricePrefix?: string;
  addonsHeadline?: string;
  addons?: Array<{
    label?: string;
    price?: string;
    note?: string;
    _type: 'addon';
    _key: string;
  }>;
  rushHeadline?: string;
  rushBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  faqHeadline?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type HowItWorksPage = {
  _id: string;
  _type: 'howItWorksPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  stepsHeadline?: string;
  steps?: Array<{
    number?: string;
    label?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: null;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    _type: 'step';
    _key: string;
  }>;
  faqHeadline?: string;
  faqSubhead?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  stepsSubhead?: string;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroItalicWord?: string;
  heroSubhead?: string;
  heroPrimaryCtaLabel?: string;
  heroPrimaryCtaHref?: string;
  heroSecondaryCtaLabel?: string;
  heroSecondaryCtaHref?: string;
  trustItems?: Array<string>;
  marqueeEyebrow?: string;
  categoriesEyebrow?: string;
  categoriesHeadline?: string;
  categoriesSubhead?: string;
  categoriesNote?: string;
  aboutEyebrow?: string;
  aboutHeadline?: string;
  aboutBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  aboutPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  makerQuote?: string;
  makerSignature?: string;
  makerFacts?: Array<string>;
  aboutCtaLabel?: string;
  aboutCtaHref?: string;
  processEyebrow?: string;
  processHeadline?: string;
  processSubhead?: string;
  processSteps?: Array<{
    number?: string;
    label?: string;
    body?: string;
    _type: 'processStep';
    _key: string;
  }>;
  processCtaLabel?: string;
  processCtaHref?: string;
  wallEyebrow?: string;
  wallHeadline?: string;
  wallSubhead?: string;
  wallCtaLabel?: string;
  finalEyebrow?: string;
  finalHeadline?: string;
  finalSubhead?: string;
  finalCtaLabel?: string;
  finalCtaHref?: string;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  galleryEyebrow?: string;
  galleryHeadline?: string;
  gallerySubhead?: string;
  galleryCtaLabel?: string;
  galleryCtaHref?: string;
  ctaEyebrow?: string;
  ctaHeadline?: string;
  ctaSubhead?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TrashedItem
  | StudioPlaybook
  | StudioNotes
  | StudioGuide
  | FaqItem
  | SanityImageAssetReference
  | ClearanceItem
  | SanityImageCrop
  | SanityImageHotspot
  | PricingTier
  | ItemCategoryReference
  | FontReference
  | GalleryItem
  | ThreadColor
  | Slug
  | Font
  | NotFoundPage
  | AtelierSettings
  | SiteSettings
  | HomePageReference
  | HowItWorksPageReference
  | PricingPageReference
  | AboutPageReference
  | RequestAQuotePageReference
  | ShopIndexPageReference
  | StyleGalleryPageReference
  | FontGuidePageReference
  | ThreadChartPageReference
  | ClearancePageReference
  | ThankYouPageReference
  | LegalPageReference
  | NavLink
  | LegalPage
  | ItemCategory
  | ThankYouPage
  | ClearancePage
  | ThreadChartPage
  | FontGuidePage
  | StyleGalleryPage
  | ShopIndexPage
  | RequestAQuotePage
  | AboutPage
  | PricingPage
  | HowItWorksPage
  | HomePage
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
