// Safe to edit by hand
// The @sanity/icons component for each guide icon name in ./iconNames.ts.
// Split out so the guide content stays plain data that a Node unit test can
// import without React. The Record type makes a missing name a compile error.
// (Pattern from fbcm, src/sanity/guides/icons.ts.)
import type { ComponentType } from 'react';
import {
  BasketIcon,
  BulbOutlineIcon,
  CalendarIcon,
  ChartUpwardIcon,
  CircleIcon,
  ClipboardImageIcon,
  ClockIcon,
  ColorWheelIcon,
  CreditCardIcon,
  DocumentTextIcon,
  DownloadIcon,
  EarthAmericasIcon,
  EditIcon,
  EnvelopeIcon,
  FolderIcon,
  HeartIcon,
  HelpCircleIcon,
  ImageIcon,
  MobileDeviceIcon,
  PinIcon,
  PublishIcon,
  SearchIcon,
  SparkleIcon,
  StarIcon,
  TagIcon,
  TextIcon,
  ThLargeIcon,
  ThListIcon,
  TrashIcon,
  UndoIcon,
  UsersIcon,
  WarningOutlineIcon,
  BulbFilledIcon,
  FaceHappyIcon,
  CommentIcon,
  MarkerIcon,
} from '@sanity/icons';
import type { GuideIconName } from './iconNames.ts';

export const GUIDE_ICONS: Record<GuideIconName, ComponentType> = {
  wave: FaceHappyIcon,
  publish: PublishIcon,
  undo: UndoIcon,
  edit: EditIcon,
  page: DocumentTextIcon,
  phone: MobileDeviceIcon,
  tag: TagIcon,
  question: HelpCircleIcon,
  sparkle: SparkleIcon,
  image: ImageIcon,
  circle: CircleIcon,
  basket: BasketIcon,
  card: CreditCardIcon,
  text: TextIcon,
  color: ColorWheelIcon,
  folder: FolderIcon,
  clock: ClockIcon,
  warning: WarningOutlineIcon,
  search: SearchIcon,
  trash: TrashIcon,
  help: BulbOutlineIcon,
  list: ThListIcon,
  heart: HeartIcon,
  star: StarIcon,
  pin: PinIcon,
  globe: EarthAmericasIcon,
  users: UsersIcon,
  chart: ChartUpwardIcon,
  qr: ThLargeIcon,
  download: DownloadIcon,
  brush: BulbFilledIcon,
  envelope: EnvelopeIcon,
  calendar: CalendarIcon,
  camera: ClipboardImageIcon,
  megaphone: CommentIcon,
  map: MarkerIcon,
};
